language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
script: './gradlew build check'
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key: "fa5a9b2a2fde4d82a4fa75354d005128c4a4dd80"
  file: /home/travis/build/rohandhamapurkar/beproj-android/app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: rohandhamapurkar/beproj-android
    #tags: true
